In [1]:
import numpy as np

In [2]:
vec1 = np.array([3, 6, 7, 2, 4, 5])
print(vec1)

[3 6 7 2 4 5]


In [3]:
vec2 = np.array([[3], [6], [7], [2], [4], [5]])
print(vec2)

[[3]
 [6]
 [7]
 [2]
 [4]
 [5]]


In [4]:
x = np.arange(-10.0, 10.01, 0.01)
print(x)

[-10.    -9.99  -9.98 ...   9.98   9.99  10.  ]


In [5]:
np.random.seed(0)
vec3 = np.random.random(15)
print(vec3)
vec3 = np.random.randint(0, 21, 15)
print(vec3)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606]
[ 9 20 19 16 19  5 15 15  0 18  3 17 19 19 19]


In [6]:
print("Все элементы после 5:", vec3[5:])
print("Все элементы до 10:", vec3[:9])
print("Все элементы между 3 и 12:", vec3[3:11])
print("Первый элемент:", vec3[0])
print("Последний элемент:", vec3[-1])
print("Без элементов с 4 по 8:", np.delete(vec3, [3, 4, 5, 6, 7, 8]))
print("Каждый второй элемент:", vec3[1::2])

Все элементы после 5: [ 5 15 15  0 18  3 17 19 19 19]
Все элементы до 10: [ 9 20 19 16 19  5 15 15  0]
Все элементы между 3 и 12: [16 19  5 15 15  0 18  3]
Первый элемент: 9
Последний элемент: 19
Без элементов с 4 по 8: [ 9 20 19 18  3 17 19 19 19]
Каждый второй элемент: [20 16  5 15 18 17 19]


In [7]:
mat1 = np.array([[2, 4, 6], [-3, 5, 1], [7, 4, 5]])
print(mat1)

[[ 2  4  6]
 [-3  5  1]
 [ 7  4  5]]


In [8]:
print("Количество строк:", np.shape(mat1)[0])
print("Количество столбцов:", np.shape(mat1)[1])
print("Количество элементов:", np.size(mat1))
print("Количество размерностей:", np.ndim(mat1))

Количество строк: 3
Количество столбцов: 3
Количество элементов: 9
Количество размерностей: 2


In [9]:
print("Максимум в векторе:", vec3.max())
print("Максимум в матрице:", mat1.max())
print("Минимум в векторе:", vec3.min())
print("Минимум в матрице:", mat1.min())
print("Среднее в векторе:", vec3.mean())
print("Среднее в матрице:", mat1.mean())
print("Дисперсия в векторе:", vec3.var())
print("Дисперсия в матрице:", mat1.var())
print("Стандартное отклонение в векторе:", vec3.std())
print("Стандартное отклонение в матрице:", mat1.std())
print("Отсортированный вектор:", np.sort(vec3))
print("Отсортированная матрица:")
print(np.sort(mat1))

Максимум в векторе: 20
Максимум в матрице: 7
Минимум в векторе: 0
Минимум в матрице: -3
Среднее в векторе: 14.2
Среднее в матрице: 3.4444444444444446
Дисперсия в векторе: 40.959999999999994
Дисперсия в матрице: 8.246913580246913
Стандартное отклонение в векторе: 6.3999999999999995
Стандартное отклонение в матрице: 2.871743996293352
Отсортированный вектор: [ 0  3  5  9 15 15 16 17 18 19 19 19 19 19 20]
Отсортированная матрица:
[[ 2  4  6]
 [-3  1  5]
 [ 4  5  7]]


In [10]:
vec4 = np.arange(-5, 25, 1)
print("Начальный массив:")
print(vec4)

Начальный массив:
[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
 19 20 21 22 23 24]


In [11]:
add_2 = lambda x: x+2
a = np.vectorize(add_2)(vec4)
print("Массив после прибавления 2 к каждому элементу:")
print(a)

Массив после прибавления 2 к каждому элементу:
[-3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
 21 22 23 24 25 26]


In [12]:
maxv = np.amax(vec4)
print("Максимальный элемент в массиве:", maxv)
sub_maxv = lambda x: x/maxv
a = np.vectorize(sub_maxv)(vec4)
print("Массив после деления каждого элемента на "+str(maxv)+":")
print(a)

Максимальный элемент в массиве: 24
Массив после деления каждого элемента на 24:
[-0.20833333 -0.16666667 -0.125      -0.08333333 -0.04166667  0.
  0.04166667  0.08333333  0.125       0.16666667  0.20833333  0.25
  0.29166667  0.33333333  0.375       0.41666667  0.45833333  0.5
  0.54166667  0.58333333  0.625       0.66666667  0.70833333  0.75
  0.79166667  0.83333333  0.875       0.91666667  0.95833333  1.        ]


In [13]:
nul_even = lambda x: 0 if x % 2 == 0 else x
a = np.vectorize(nul_even)(vec4)
print("Массив после замены чётных элементов на 0:")
print(a)

Массив после замены чётных элементов на 0:
[-5  0 -3  0 -1  0  1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0
 19  0 21  0 23  0]


In [14]:
n_zero_p_double = lambda x: 0 if x < 0 else x*2
a = np.vectorize(n_zero_p_double)(vec4)
print("Массив после замены отрицательных элементов на 0 и умножения положительных на 2:")
print(a)

Массив после замены отрицательных элементов на 0 и умножения положительных на 2:
[ 0  0  0  0  0  0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36
 38 40 42 44 46 48]


In [15]:
mat2 = vec4.reshape((5, 6))
print("Начальная матрица:")
print(mat2)

Начальная матрица:
[[-5 -4 -3 -2 -1  0]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [16]:
a = np.vectorize(add_2)(mat2)
print("Матрица после прибавления 2 к каждому элементу:")
print(a)

Матрица после прибавления 2 к каждому элементу:
[[-3 -2 -1  0  1  2]
 [ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]
 [15 16 17 18 19 20]
 [21 22 23 24 25 26]]


In [17]:
maxv = np.amax(mat2)
print("Максимальный элемент в матрице:", maxv)
a = np.vectorize(sub_maxv)(mat2)
print("Матрица после деления каждого элемента на "+str(maxv)+":")
print(a)

Максимальный элемент в матрице: 24
Матрица после деления каждого элемента на 24:
[[-0.20833333 -0.16666667 -0.125      -0.08333333 -0.04166667  0.        ]
 [ 0.04166667  0.08333333  0.125       0.16666667  0.20833333  0.25      ]
 [ 0.29166667  0.33333333  0.375       0.41666667  0.45833333  0.5       ]
 [ 0.54166667  0.58333333  0.625       0.66666667  0.70833333  0.75      ]
 [ 0.79166667  0.83333333  0.875       0.91666667  0.95833333  1.        ]]


In [18]:
a = np.vectorize(nul_even)(mat2)
print("Матрица после замены чётных элементов на 0:")
print(a)

Матрица после замены чётных элементов на 0:
[[-5  0 -3  0 -1  0]
 [ 1  0  3  0  5  0]
 [ 7  0  9  0 11  0]
 [13  0 15  0 17  0]
 [19  0 21  0 23  0]]


In [19]:
a = np.vectorize(n_zero_p_double)(mat2)
print("Массив после замены отрицательных элементов на 0 и умножения положительных на 2:")
print(a)

Массив после замены отрицательных элементов на 0 и умножения положительных на 2:
[[ 0  0  0  0  0  0]
 [ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]
 [38 40 42 44 46 48]]


In [20]:
a = np.random.randint(low = -5, high = 15, size = 60)
print("Сгенерированный одномерный массив:")
print(a)

Сгенерированный одномерный массив:
[ 9  2 -5 -4  4 -5  5 -2  6 13 -3 -5 -5 -1  0  1  3 12 10 -1  4  5 -4 -4
  2  4 -2  1  6  9 13 -5  9 -2  7  5  6 -1  1 -1 10 -2  7 -1  3  9 10 -2
 10  8 11 12  0  4 -2 -5  0 -5 12 13]


In [21]:
a1 = a.reshape(2, -1)
print("Одномерный массив, преобразованный в двумерный массив:")
print(a1)

Одномерный массив, преобразованный в двумерный массив:
[[ 9  2 -5 -4  4 -5  5 -2  6 13 -3 -5 -5 -1  0  1  3 12 10 -1  4  5 -4 -4
   2  4 -2  1  6  9]
 [13 -5  9 -2  7  5  6 -1  1 -1 10 -2  7 -1  3  9 10 -2 10  8 11 12  0  4
  -2 -5  0 -5 12 13]]


In [22]:
a2 = a.reshape(3, 4, -1)
print("Одномерный массив, преобразованный в трёхмерный массив:")
print(a2)

Одномерный массив, преобразованный в трёхмерный массив:
[[[ 9  2 -5 -4  4]
  [-5  5 -2  6 13]
  [-3 -5 -5 -1  0]
  [ 1  3 12 10 -1]]

 [[ 4  5 -4 -4  2]
  [ 4 -2  1  6  9]
  [13 -5  9 -2  7]
  [ 5  6 -1  1 -1]]

 [[10 -2  7 -1  3]
  [ 9 10 -2 10  8]
  [11 12  0  4 -2]
  [-5  0 -5 12 13]]]


In [23]:
a = np.random.randint(low = -5, high = 15, size = (2, 12))
print("Сгенерированная матрица:")
print(a)

Сгенерированная матрица:
[[-1 -3 11 -2 -3  5  8 11  2  4 -5  5]
 [13  6 -3 -3 -2 -2 13  9 -2 12 13  9]]


In [24]:
a2 = a.reshape(3, 2, -1)
print("Матрица, преобразованная в трёхмерный массив:")
print(a2)

Матрица, преобразованная в трёхмерный массив:
[[[-1 -3 11 -2]
  [-3  5  8 11]]

 [[ 2  4 -5  5]
  [13  6 -3 -3]]

 [[-2 -2 13  9]
  [-2 12 13  9]]]


In [25]:
m1 = np.random.randint(low = -5, high = 15, size = (4, 6))
print("Сгенерированная матрица:")
print(m1)

Сгенерированная матрица:
[[ 4 -4 -1  5  6  3]
 [ 6 -3 14 11 -5 -5]
 [ 1 14  9  5 14  3]
 [ 8 -3 -2 -3  6  8]]


In [26]:
print("Транспонированная матрица:")
print(m1.T)

Транспонированная матрица:
[[ 4  6  1  8]
 [-4 -3 14 -3]
 [-1 14  9 -2]
 [ 5 11  5 -3]
 [ 6 -5 14  6]
 [ 3 -5  3  8]]


In [27]:
m2 = np.random.randint(low = -5, high = 15, size = (6, 4))
print("Сгенерированная новая матрица:")
print(m2)

Сгенерированная новая матрица:
[[11  3  3 14]
 [ 3 -3 -2  7]
 [ 9 -5 -1 -2]
 [ 8  6  8  8]
 [ 6 11  9 11]
 [14 -4  3 -5]]


In [28]:
print("Произведение матриц:")
print(np.dot(m1, m2))

Произведение матриц:
[[141 113 124 121]
 [171 -12  38  93]
 [300  88 141 273]
 [185  59  86  97]]


In [29]:
m2 = m2.reshape((4, 6))
print("Матрица с изменённой формой:")
print(m2)

Матрица с изменённой формой:
[[11  3  3 14  3 -3]
 [-2  7  9 -5 -1 -2]
 [ 8  6  8  8  6 11]
 [ 9 11 14 -4  3 -5]]


In [30]:
print("Сложение матриц:")
print(m1+m2)

Сложение матриц:
[[15 -1  2 19  9  0]
 [ 4  4 23  6 -6 -7]
 [ 9 20 17 13 20 14]
 [17  8 12 -7  9  3]]


In [31]:
print("Поэлементное произведение матриц:")
print(m1*m2)

Поэлементное произведение матриц:
[[ 44 -12  -3  70  18  -9]
 [-12 -21 126 -55   5  10]
 [  8  84  72  40  84  33]
 [ 72 -33 -28  12  18 -40]]


In [32]:
a1 = np.arange(-5, 10, 2.5)
a2 = np.arange(3, 9, 1)
print("Первый сгенерированный вектор:")
print(a1)
print("Второй сгенерированный вектор:")
print(a2)
print("Скалярное произведение векторов:")
print(np.dot(a1, a2))

Первый сгенерированный вектор:
[-5.  -2.5  0.   2.5  5.   7.5]
Второй сгенерированный вектор:
[3 4 5 6 7 8]
Скалярное произведение векторов:
85.0
